### PR TITLE
DF-3: Edit note.txt.

### PR DESCRIPTION
**Pull request by dnquangit**

### CODE REVIEW

**Review by cml-kit — APPROVED** [review]

**Review by cml-kit — APPROVED** [review]
okie

**Review by cml-kit — APPROVED** [review]
okie

**Review by cml-kit — APPROVED** [review]

**Review by dnquangit — COMMENTED** [review]
okie

**Review by cml-kit — APPROVED** [review]

**Review by cml-kit — APPROVED** [review]
all are good then

**Pull request merged**
